config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root 'welcome#index', as: 'user_root'
  post 'code/hi'
  get 'code/hi'
  post 'code/new'
  get 'code/new'
  get 'multiplayer/change_level'
  post 'multiplayer/change_level'
  post 'multiplayer/new'
  post 'multiplayer/connecting'
  post 'multiplayer/disconnect'
  get 'multiplayer/set_pos'
  post 'multiplayer/set_pos'
  post 'multiplayer/index'
  post 'welcome/generate_code'
  get 'welcome/generate_code'
  post 'welcome/index'
  get 'welcome/index'
  get 'multiplayer/index', as: 'multiplayer'
  post 'multiplayer/index'
  get 'singleplayer/index', as: 'singleplayer'
  resources :welcome do
    member do
      post 'new'
    end
  end

  resources :persons do
    collection do
      post 'profile'
      get 'profile'
      post 'generate'
      post 'index'
    end
  end
end

app/controllers/multiplayer_controller.rb
class MultiplayerController < ApplicationController
  skip_before_filter :verify_authenticity_token, only: [:index]
  before_filter :check_for_signed_in
  def index
    if user_signed_in?
      @user = User.where(email: current_user.email).take
      @current_game = if @user.playersid == '1'
                        Field.where(player1: current_user.email).take
                      end
      map = Level.find(@user.user_level)
      if @current_game.nil?
        @level_map = map.data
      else
        if user_signed_in? && @current_game.save_game == 0 && !@current_game.nil?
          @level_map = map.data
        else
          @level_map = @current_game.map
        end

        @save_level = params[:lvlmap]
        # Запись в бд
        unless @save_level.nil?
          @current_game.map = @save_level
          @current_game.save_game = 1
          @current_game.save
        end
      end
    end

    @games = Field.where(online_players: '1')
    @ingames = Field.where(online_players: '2')
  end

  def new
    unless Field.exists?(player1: current_user.email) # && !Field.exists?(player2: current_user.email)
      @field = Field.new
      @field.player2 = nil
      Field.CreatingField(@field, current_user.email)

      @user = User.where(email: current_user.email).take
      @user.playersid = 1
      @user.field_id = @field.id
      @user.save
    end
    redirect_to multiplayer_index_path
 end

  def connecting
    unless Field.exists?(player1: current_user.email)
      @currentmail = params[:currentgame]
      @field = Field.where(player1: @currentmail).take
      Field.ConnectingField(@field, current_user.email)
    end
    unless Field.exists?(player1: current_user.email)
      @user = User.where(email: current_user.email).take
      @user.playersid = @field.player2.index(current_user.email) + 2
      @user.field_id = @field.id
      @user.save
    end
    redirect_to multiplayer_index_path
  end

  def disconnect
    @user = User.where(email: current_user.email).take
    if @user.playersid == '1'
      @field = Field.where(player1: current_user.email)
      @game = Field.where(player1: current_user.email).take
      @user.playersid = nil
      @user.field_id = nil
      unless @game.player2.nil?
        @game.player2.each do |user|
          @user_2 = User.where(email: user).take
          @user_2.playersid = nil
          @user_2.field_id = nil
          @user_2.save
        end
      end
      @field.destroy_all
      @user.save
    else
      @field = Field.where(id: @user.field_id).take
      @field.player2.delete(current_user.email)
      @field.save
      @user = User.where(email: current_user.email).take
      @user.playersid = nil
      @user.field_id = nil
      @user.save
    end
    redirect_to multiplayer_index_path
  end

  def set_pos
    # pos_writing
    if user_signed_in?
      user_id = params[:user_id]
      pos_x = params[:pos_x]
      pos_y = params[:pos_y]
      pos_i = params[:pos_i]
      @user = User.where(id: user_id).take
      if pos_x.nil? && pos_y.nil? && pos_i.nil?
      else
        @user.player_x = pos_x
        @user.player_y = pos_y
        @user.player_i = pos_i
        @user.save
      end
    end
    respond_to do |format|
      format.html
      format.json { render json: @user }
    end
  end
end

app/views/multiplayer/index.html.erb
<script>
	var port = '<%=APP_CONFIG[:ws_m_port]%>';
	var level_map = JSON.parse('<%=@level_map%>');
	var player = '<%= current_user.playersid %>';
	var host_player_f_id = '<%= current_user.field_id %>'
	var host_player = '<%= current_user.email %>'
</script>

<script type = 'text/javascript' src = '<%= asset_path('multi_game.js.erb') %>'></script>
<script type = 'text/javascript' src = '<%= asset_path('multi_bullet_logic.js') %>'></script>
<script type = 'text/javascript' src = '<%= asset_path('multi_player_logic.js') %>'></script>

<div class="header">
	<div class="row">
		<div class="col-md-4">
			<div class="exit_btn">
				<%=link_to(image_tag("btn_back.png"),user_root_path)%>
				<p><%= link_to 'В меню', user_root_path %></p>
			</div>
		</div>
		<div class="col-md-4 title_game">
			<h1 align="center">Battle city multiplayer</h1>
		</div>
		<div class="col-md-4 hi">
			<% if user_signed_in?%>
			<div class="col-md-6"></div>
			<div class="col-md-6">
				<p>	Здравствуйте,</p>
					<p><%=current_user.email %> <%= link_to "Выйти", destroy_user_session_path, :method => :delete %>
				</p>
			</div>
			<% end %>
		</div>
	</div>
</div>

<div class="game_section_mp">
	<div class="row">
			<div class="col-md-6 col-xs-6">
				<canvas align="left" id="map" width="624" height="624"></canvas>
			</div>

			<div class="col-md-6 col-xs-6">
				<div class="row game_btn">
					<%= button_to "Создать игру", multiplayer_new_path %>
					<%= button_to "Удалить(отключиться)", multiplayer_disconnect_path%>
					<button onclick = 'post_level_map()'>Сохранить карту</button>
				</div>

				<div class="row game_list">
				  <div class="col-md-6 avaleb_games">
						<h2>Доступные игры</h2>
						<hr>
						<%@games.each do |game|%>
							<ul>
								<li>
									<%= game.player1 %>
									<%= button_to "присоединится", multiplayer_connecting_path(:currentgame => game.player1) %>
								</li>
							</ul>
						<% end %>
					</div>
					<div class='col-md-6 ingame'>
						<h2>Идет игра</h2>
						<hr>
						<%@ingames.each do |game|%>
							<ul>

									<li><%=game.player1%> VS <%=game.player2.size%></li>
									<%= button_to "присоединится", multiplayer_connecting_path(:currentgame => game.player1) %>
								

							</ul>
						<% end %>
					</div>
				</div>

			</div>
		</div>
	</div>
</div>