config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root 'welcome#index', as: 'user_root'
  post 'code/hi'
  get 'code/hi'
  post 'code/new'
  get 'code/new'
  get 'multiplayer/change_level'
  post 'multiplayer/change_level'
  post 'multiplayer/new'
  post 'multiplayer/connecting'
  post 'multiplayer/disconnect'
  get 'multiplayer/set_pos'
  post 'multiplayer/set_pos'
  post 'multiplayer/index'
  post 'welcome/generate_code'
  get 'welcome/generate_code'
  post 'welcome/index'
  get 'welcome/index'
  get 'multiplayer/index', as: 'multiplayer'
  post 'multiplayer/index'
  get 'singleplayer/index', as: 'singleplayer'
  resources :welcome do
    member do
      post 'new'
    end
  end

  resources :persons do
    collection do
      post 'profile'
      get 'profile'
      post 'generate'
      post 'index'
    end
  end
end

app/controllers/welcome_controller.rb
# WelcomeController
class WelcomeController < ApplicationController
  def index
  end

  def generate_code
    @user = User.where(email: current_user.email).take
    @user.generate_code
    respond_to do |format|
      format.js { render json: @user }
    end
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/index.html.erb
<script type="text/javascript">
	function generate_code() {
		$.ajax({
	    url: "/welcome/generate_code",
	    type: "post",
	    dataType: "json",
	    success: function (data) {
				$("#code").text('Ваш код: ' +  data.code);
				$("#qrcode").html(data.qrcode);
		 }
	  });
	}
</script>

<div class="col-md-3">
</div>
<div id="user_nav" class='col-md-6'>

	<% if user_signed_in?%>

		<p> Перед тем как выбрать режим игры, синхронизируйтесь с вашим устройсвом.
			Для этого сгенерируйте код и введите его на Вашем телефоне
		</p>
		<button href="#myModal" class="btn btn-primary" data-toggle="modal" onclick = 'generate_code()'>Сгенерировать код</button>
		<br><br>
	<!-- HTML-код модального окна -->
	<div id="myModal" class="modal fade">
	  <div class="modal-dialog">
	    <div class="modal-content">
	      <!-- Заголовок модального окна -->
	      <div class="modal-header">
	        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
	        <h4 class="modal-title">Ваш код</h4>
	      </div>
	      <!-- Основное содержимое модального окна -->
	      <div class="modal-body">
					<div id = 'code'>Ваш код:</div>
					<div id="qrcode"></div>
	      </div>
	    </div>
	  </div>
	</div>

		<ul>
			<li>
      	<%= link_to 'multiplayer', multiplayer_path %>
			</li>
			<li>
      	<%= link_to 'singleplayer', singleplayer_path %>
			</li>
	</ul>
  <% else %>
		<p class="welcome_signin">
	Для начала пожалуйста <%= link_to "зарегистрируйтесь", new_user_registration_path %> или
		<%= link_to "выполните вход", new_user_session_path %>
		<br>
		Можете использовать кнопки социальных сетей для авторизации</p>
		<%=link_to(image_tag("vkontakte.ico"),user_vkontakte_omniauth_authorize_path)%>
		<%=link_to(image_tag("email.ico"),user_mailru_omniauth_authorize_path)%>
		<%=link_to(image_tag("facebook.ico"),user_facebook_omniauth_authorize_path)%>
		<%=link_to(image_tag("twitter.ico"),user_twitter_omniauth_authorize_path)%>
	<% end %>

</div>
<div class="col-md-3 hi">
	<% if user_signed_in?%>
	<div class="col-md-6"></div>
	<div class="col-md-6">
		<p>	Здравствуйте,</p>
			<p><%=current_user.email %> <%= link_to "Выйти", destroy_user_session_path, :method => :delete %>
		</p>
	</div>
	<% end %>
</div>